# Adapted from 
# http://gronlier.fr/blog/2015/01/adding-code-coverage-to-your-c-project/
sudo: required
dist: trusty
env:
    matrix:
        - USE_HDFS="ON" USE_MPI="ON"
        - USE_HDFS="ON" USE_MPI="OFF"
        - USE_HDFS="OFF" USE_MPI="ON"
        - USE_HDFS="OFF" USE_MPI="OFF"

install:
    # Install library dependencies
    - mkdir -p $TRAVIS_BUILD_DIR/build
    - sudo scripts/install-hadoop.sh
    - if [ "$USE_HDFS" == "ON" ]; then sudo scripts/install-travis-deps.sh; fi
    # Install lcov to coveralls conversion + upload tool
    - gem install coveralls-lcov
    # Build TileDB
    - cd $TRAVIS_BUILD_DIR/build
    - cmake -DCMAKE_BUILD_TYPE=Coverage  -DTILEDB_VERBOSE=1 -DUSE_MPI=$USE_MPI -DUSE_HDFS=$USE_HDFS -DJAVA_HOME=/usr/lib/jvm/java-8-oracle/jre  -DHADOOP_HOME=/usr/local/hadoop/home ..
    - make -j4
    - make examples -j4
    
before_script:
    - lcov --directory $TRAVIS_BUILD_DIR/build --zerocounters

script:
    #- make check-format
    - if [ "$USE_HDFS" == "ON" ]; then sudo scripts/hadoop-env-variables.sh; fi
    - sudo make check

after_success:
    - cd $TILEDB_BUILD_DIR/build
    - lcov --directory . --capture --output-file coverage.info
    - lcov --list coverage.info # debug before upload
