# Adapted from 
# http://gronlier.fr/blog/2015/01/adding-code-coverage-to-your-c-project/
sudo: required
dist: trusty
env:
    matrix:
        - USE_HDFS="ON"
        - USE_HDFS="OFF"
	
install:
    # Install library dependencies
    - mkdir -p $TRAVIS_BUILD_DIR/build
    - sudo scripts/install-hadoop.sh
    - sudo scripts/install-travis-deps.sh
    # Install lcov to coveralls conversion + upload tool
    - gem install coveralls-lcov
    # Build TileDB
    - cd $TRAVIS_BUILD_DIR/build
    - cmake -DCMAKE_BUILD_TYPE=Coverage  -DTILEDB_VERBOSE=1 -DUSE_MPI=$USE_MPI ..
    - make -j4
    - make examples -j4
    
before_script:
    - lcov --directory $TRAVIS_BUILD_DIR/build --zerocounters

script:
    #- make check-format
    - make check

after_success:
    - cd $TILEDB_BUILD_DIR/build
    - lcov --directory . --capture --output-file coverage.info
    - lcov --list coverage.info # debug before upload
